### ISSUE TITLE
Unable to route to /women.html after Peregrine update in #83

### ISSUE THREAD

**Issue by philwinkle** [magento-research/venia-pwa-concept#86]
## This issue is a:
[x] Bug
[ ] Feature suggestion
[ ] Other
 

## Description:

Location prop for url resolver contains a leading slash after the Peregrine update in #83 - Graphql can't resolve a CATEGORY type for `/women.html`, expects `women.html`
 

### Environment and steps to reproduce

Rolling back to prior to #83 resolves the issue. 

OS:

Magento 2 version:

2.3

Other environment information:

Valet+ 

Steps to reproduce:

1. Update to master
2. Navigate to `/women.html`
3. No rendered page - shows only `Loading`
4. Roll back to prior to #83 (7862880)
5. Reinstall node_modules
6. Works as expected
 

## Expected result:

Should render page
 

## Possible solutions:

Address issue with new leading slash introduced to the location props given to MagentoRouteHandler component after Peregrine update

**Comment by DrewML** [comment]
Thanks @philwinkle. #83 (and https://github.com/magento-research/peregrine/pull/43 + https://github.com/magento/graphql-ce/pull/13) require that you have the latest version of `2.3-develop` running locally.

![image](https://user-images.githubusercontent.com/5233399/41299409-fdc7bebe-6e28-11e8-9468-d529d4fed558.png)


Versioning and messaging for things like this will be easier for us in the future, but right now since `2.3-develop` is a development branch, we can't pin against a specific version.

**Comment by philwinkle** [comment]
OK mayyyyyybe this should have been in the commit #83 ¯\_(ツ)_/¯
